apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: java-application
<<<<<<< HEAD
        image: nginx:66
=======
        image: nginx:56
>>>>>>> 24a673ddb56d151cfa81bae43466bf7672a174f0
        ports:
        - containerPort: 8080
