apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-rbac-cm","app.kubernetes.io/part-of":"argocd"},"name":"argocd-rbac-cm","namespace":"argocd"}}
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    p, role:developer, applications, get, my-project/*, allow
    p, role:developer, applications, create, my-project/*, allow
    p, role:developer, applications, update, my-project/*, allow
    p, role:developer, applications, delete, my-project/*, allow
    p, role:developer, projects, get, my-project, allow
    g, alice, role:admin
    p, role:admin, applications, *, */*, allow
    p, role:admin, projects, *, */*, allow
    p, role:admin, clusters, get, *, allow
    p, role:admin, clusters, update, *, allow
    p, role:admin, repositories, get, *, allow
    p, role:admin, repositories, create, *, allow
    p, role:admin, repositories, update, *, allow
    p, role:admin, repositories, delete, *, allow
  policy.default: role:readwrite

